strictness: high
test-warnings: true
doc-warnings: false

ignore-paths:
  - build
  - .git
  - __pycache__
  - .eggs
  - dist
  - .tox
  - .cachedocs
  - .pytest_cache

max-line-length: 120

mccabe:
  max-complexity: 10

pylint:
  run: false

pyroma:
  run: false

frosted:
  run: false

vulture:
  run: false

pydocstyle:
  run: false
