strictness: high
test-warnings: true
doc-warnings: false

ignore-paths:
  - build
  - .git
  - __pycache__
  - .eggs
  - dist
  - .tox
  - .cachedocs

pep8:
  options:
    max-line-length: 120

mccabe:
  max-complexity: 10

pylint:
  run: false

pyroma:
  run: false

frosted:
  run: false

vulture:
  run: false

pep257:
  run: false
