[tools]
poetry = "latest"
ruff = "latest"

[tasks.docker]
description = "Build Docker image"
run = "docker build -t aiven-poke ."

[tasks.install]
description = "Install dependencies"
run = "poetry install --no-interaction --all-groups"

[tasks.test]
description = "Run tests"
run = "poetry run pytest"
depends = ["install"]

[tasks.check]
description = "Run tests and linters"
depends = ["test", "lint", "fmt-check"]

[tasks.fmt]
description = "Format the files in the project"
run = "ruff format"

[tasks."fmt-check"]
description = "Check the formating of the files in the project"
run = "ruff format --diff"

[tasks.lint]
description = "Lint the project"
run = "ruff check"

[tasks."lint-fix"]
description = "Run automated lint fixers"
run = "ruff check --fix"
