apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aiven-poke.fullname" . }}
  labels:
    {{- include "aiven-poke.labels" . | nindent 4 }}
type: Opaque
stringData:
  AIVEN_TOKEN: '{{ .Values.aivenToken }}'
  WEBHOOK_URL: '{{ .Values.slackWebhookURL }}'
