dependencies:
  - allOf:
      - naiserator
      - aivenator
environmentKinds:
  - legacy
  - tenant
  - onprem
values:
  aivenProject:
    description: Which aiven project to look for topics and users in
    displayName: aiven project
    computed:
      template: '"{{ .Env.aiven_project }}"'
  enableTopics:
    description: Should we poke teams about topics without cluster config
    computed:
      template: |
        {{ ne .Env.kind "onprem" }}
  aivenToken:
    config:
      type: string
      secret: true
  image.pullPolicy:
    config:
      type: string
  image.repository:
    config:
      type: string
  image.tag:
    config:
      type: string
  push_gateway_address:
    config:
      type: string
  schedule:
    config:
      type: string
  slackWebhookURL:
    config:
      type: string
      secret: true
  slackWebhookEnabled:
    displayName: Slack enabled
    description: Should pokes be sent to Slack or just logged
    config:
      type: bool
  extraEnv.HTTPS_PROXY:
    displayName: HTTPS proxy
    config:
      type: string
    ignoreKind:
      - tenant
  extraEnv.NO_PROXY:
    displayName: NO_PROXY
    config:
      type: string
    ignoreKind:
      - tenant
