# Default values for aiven-poke.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

slackWebhookURL: ""
aivenToken: ""
push_gateway_address: ""
enable_expiring_users: "true"
enable_topics: "true"

extraEnv: {}

image:
  repository: europe-north1-docker.pkg.dev/nais-io/nais/images/aiven-poke
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "main"

nameOverride: ""
fullnameOverride: ""

schedule: "23 9 * * 3"
aivenProject: ""

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi