apiVersion: "nais.io/v1"
kind: "Naisjob"
metadata:
  name: aiven-poke
  namespace: aura
  labels:
    team: aura
spec:
  image: "{{ image }}"
  # TODO: Use this schedule when enabling webhook schedule: "23 9 * * 3"
  schedule: "23 * * * *"
  liveness:
    path: /isHealthy
  readiness:
    path: /isReady
  envFrom:
    - secret: aiven-poke
  env:
    - name: MAIN_PROJECT
      value: "{{ mainProject }}"
    - name: WEBHOOK_ENABLED # TODO: Remove when done testing
      value: "false"
