apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    app: aiven-poke
  name: aiven-poke-apiserver
  namespace: aura
spec:
  egress:
  - to:
    - ipBlock:
        cidr: 172.16.0.2/32
  podSelector:
    matchLabels:
      app: aiven-poke
  policyTypes:
  - Egress

