name: Build and push charts
on:
  push:
    branches:
      - main
    paths:
    - 'charts/**'
    - '.github/workflows/chart.yaml'

env:
  REGISTRY: europe-north1-docker.pkg.dev/nais-io/nais
  CHART: aiven-poke

jobs:
  build:
    permissions:
      contents: 'read'
      id-token: 'write'
    name: Build and push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: ${{ secrets.NAIS_IO_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: 'gh-${{ env.CHART }}@nais-io.iam.gserviceaccount.com'
          token_format: 'access_token'

      - name: Login to registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: "oauth2accesstoken"
          password: "${{ steps.auth.outputs.access_token }}"

      - uses: azure/setup-helm@v3
        name: 'Setup Helm'
        with:
          version: '3.10.1'

      - name: Build Chart
        run: |-
          helm package charts

      - name: Push Chart
        run: |-
          helm push "${{ env.CHART }}*.tgz" "oci://${{ env.REGISTRY }}"
