name: Create docker image

on:
  push:
    paths:
    - 'aiven_poke/**'
    - 'tests/**'
    - 'Earthfile'
    - 'pyproject.toml'
    - 'poetry.lock'
    - '.prospector.yaml'
    - '.github/workflows/main.yaml'

env:
  REGISTRY: ghcr.io/nais
  IMAGE_NAME: aiven-poke

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - name: Install earthly
        uses: earthly/actions-setup@v1
        with:
          version: "latest" # or pin to an specific version, e.g. "v0.6.10"

      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: "Set image tag"
        id: set-image-tag
        run: |
          export IMAGE_TAG="$(date +%Y%m%d%H%M%S)-$(git describe --always --dirty --exclude '*')"
          echo "IMAGE_TAG=${IMAGE_TAG}" >> ${GITHUB_ENV}
          echo "image_tag=${IMAGE_TAG}" >> ${GITHUB_OUTPUT}

          export IMAGE="${REGISTRY}/${IMAGE_NAME}"
          echo "IMAGE=${IMAGE}" >> $GITHUB_ENV

          echo "image=${IMAGE}:${IMAGE_TAG}" >> ${GITHUB_OUTPUT}

      - name: Build and possibly push
        env:
          EARTHLY_PUSH: "${{ github.ref == 'refs/heads/main' }}"
        run: |
          earthly --version
          earthly --ci +docker --IMAGE_TAG="${IMAGE_TAG}" --BASEIMAGE="${IMAGE}"
    outputs:
      image: "${{ steps.set-image-tag.outputs.image }}"
      image_tag: "${{ steps.set-image-tag.outputs.image_tag }}"
# XXX: Deploy to fasit doesn't work when feature is only available in legacy clusters because of no CI cluster
#  deploy-fasit:
#    name: Deploy to Fasit
#    if: github.ref == 'refs/heads/main'
#    runs-on: fasit-deploy
#    permissions:
#      contents: read
#      id-token: write
#    needs:
#      - build
#    steps:
#      - uses: nais/fasit-deploy@main
#        with:
#          json: '{"image": {"tag": "${{ needs.build.outputs.image_tag }}"}}'
#          feature_name: aiven-poke
